export const careers = [
    "Multiple Careers",
    "Creative Arts/Design",
    "Engineering/Manufacturing",
    "Education",
    "Entrepreneurship",
    "Investing/Finance",
    "Government/Legal",
    "Healthcare",
    "Human Resources",
    "Leisure/Sports/Tourism",
    "Law",
    "Marketing/Public Relations",
    "Non-Profit",
    "Police/Fire/Security",
    "Real Estate/Construction",
    "Sales",
    "Veterinarian",
    "Small Business Owner",
    "Other",
];
